import { Column, CreateDateColumn, Entity, Index, JoinColumn, ManyToOne, PrimaryColumn } from 'typeorm';
import { TicketEntity } from '../tickets/ticket.entity';

/** An uploaded image. The bytes live in the S3 bucket under `storageKey`; this row is the index. */
@Entity({ name: 'attachments' })
export class AttachmentEntity {
  /** Generated by the service before the upload (it is part of the storage key). */
  @PrimaryColumn({ type: 'uuid' })
  id!: string;

  @Column({ name: 'storage_key', type: 'varchar', length: 300, unique: true })
  storageKey!: string;

  @Column({ name: 'original_filename', type: 'varchar', length: 255 })
  originalFilename!: string;

  @Column({ name: 'content_type', type: 'varchar', length: 100 })
  contentType!: string;

  @Column({ name: 'size_bytes', type: 'int' })
  sizeBytes!: number;

  @Column({ type: 'int', nullable: true })
  width!: number | null;

  @Column({ type: 'int', nullable: true })
  height!: number | null;

  /** Optional: images are usually uploaded before the ticket exists. */
  @Index('IDX_attachments_ticket_id')
  @Column({ name: 'ticket_id', type: 'uuid', nullable: true })
  ticketId!: string | null;

  @ManyToOne(() => TicketEntity, { onDelete: 'SET NULL', nullable: true })
  @JoinColumn({ name: 'ticket_id', foreignKeyConstraintName: 'FK_attachments_ticket_id' })
  ticket?: TicketEntity | null;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt!: Date;
}
